import {executeSelect as execSelect} from "./queryRunners/select"
import {executeUpdate as execUpdate} from "./queryRunners/update"
import {executeDelete as execDelete} from "./queryRunners/delete"
import {executeInsert as execInsert} from "./queryRunners/insert"
import {formatAndCleanQuery, determineStatementType} from './parser/queryParser';

/**
 * Executes the given query against the current active
 * database for the given user.
 * @param query: {string} - query to be executed
 * @param dataBase: {Object} - database object generated by the database() method
 *                             implemented in the Firebase admin sdk
 * @param commitResults: {boolean} - indicates if results should be committed to the
 *                                   database when performing update, delete,
 *                                   and insert.
 *
 * @return a JSON object representing the result of the query
 */
export const executeQuery = (query, dataBase, commitResults) => {
    let clean_query = formatAndCleanQuery(query);
    const statementType = determineStatementType(clean_query);

    switch (statementType) {
        case "select":
            return execSelect(query, dataBase);
        case "update":
            return execUpdate(query, dataBase, commitResults);
        case "delete":
            return execDelete(query, dataBase, commitResults);
        case "insert":
            return execInsert(query, dataBase, commitResults);
        case "invalid":
            throw new Error("Invalid SQL query. Query must be of type SELECT, UPDATE, DELETE, or INSERT");
        default:
            throw new Error("executeQuery(): executing default statement, something is very wrong");
    }
}